### ISSUE TITLE
How can I *exclude* one or more properties from being cloned?

### ISSUE THREAD

**Issue by marcscheuner** [laazyj/GeorgeCloney#3]
Assume I have a class like this:

    public class Person
    {
        public int PersonId { get; set; }
        
        public string Name { get; set; }
        public string Firstname { get; set; }
    }

It is *not* marked as serializable - just a plain old CLR class.

How can I tell GeorgeCloney *not* to clone my "primary key" - "PersonId" ? I tried `[NonSerialized]` but that can only be applied to fields - not properties. Any other way?

**Comment by laazyj** [comment]
Currently there is no supported way of excluding public properties from being cloned.

**Comment by marc-at-nowhow** [comment]
Then this should be taken as a *feature request* - this is something I most definitely would need ...

**Comment by laazyj** [comment]
Sorry but I'm not doing any active development on this. Please send a pull request if you have a good idea on how to implement
